name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_username }}
          key: ${{ secrets.VPS_PASSWD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            touch 1.txt
            ls -al
